# Generated by Django 4.0.3 on 2022-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_category_options_alter_product_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='app1.product'),
        ),
    ]
