# Generated by Django 4.0.3 on 2022-03-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_product_user_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='user',
        ),
    ]
