# Generated by Django 4.0.3 on 2022-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_product_quantity_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
